# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcomp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdocument',
            name='csv_file',
            field=models.FileField(upload_to=b''),
        ),
    ]
