# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise_comparisons', '0004_auto_20170626_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvDocument',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to=b''),
        ),
    ]
