# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import pairwise_comparisons.models


class Migration(migrations.Migration):

    dependencies = [
        ('pairwise_comparisons', '0005_auto_20170626_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='root_dir',
            field=models.CharField(default='Output', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to=pairwise_comparisons.models.comp_upload_path),
        ),
    ]
